dataset:
  class_path: dataset.TestTimeAdaptationDataset
  args:
    dataset_path: /Users/maria/FaG/cs461_assignment2/shared/part1/data/

model:
  class_path: models.load_base_model
  args: 
    ckpt_path: /Users/maria/FaG/cs461_assignment2/shared/part1/data/pretrained_cifar10_resnet50.pt


evaluation:
  device: mps
  split: null
  max_batches: null
  reset_between_scenarios: true
  batch_size: 256