model:
  class_path: models.submission.Submission
  args: 
    embed_dim: 3072
    num_classes: 7
    hidden_dims: [1024, 512, 256]
    attention_dim: 256
    top_k_ratio: 0.5
    min_patches: 5

  best_weight_path: ckpts/best_submission.pt


dataset:
  collate_fn: models.submission.attention_collate_fn
